stages:
  - build
  - push

variables:
  IMAGE: registry.gitlab.com/reg.hinnant-group/enterprise_version_ticketsystem/django-app:latest

build-image:
  stage: build
  tags:
    - local
  script:
    - echo "Building Docker image..."
    - docker build -t $IMAGE .

push-image:
  stage: push
  tags:
    - local
  script:
    - echo "Logging into GitLab registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

    - echo "Pushing image..."
    - docker push $IMAGE
