scan:
  stage: scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --format template --template "@contrib/gitlab.tpl" -o gl-container-scanning-report.json registry.gitlab.com/reg.hinnant-group/enterprise_version_ticketsystem:latest
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
