apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/hinn/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 24 Apr 2026 05:51:04 MDT
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: cluster_info
    server: https://127.0.0.1:32776
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 24 Apr 2026 05:51:04 MDT
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /home/hinn/.minikube/profiles/minikube/client.crt
    client-key: /home/hinn/.minikube/profiles/minikube/client.key
