apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django
          image: registry.gitlab.com/reg.hinnant-group/enterprise_version_ticketsystem/django-app:latest  
            # SAFE placeholder (replace later with GHCR)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
