apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - image: ghcr.io/rhinnant/django-app:latest
        imagePullPolicy: Always
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
