# Generated by Django 6.0.4 on 2026-05-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='running', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('scan_profile', models.CharField(default='service', max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('severity', models.CharField(default='Medium', max_length=50)),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('discovered_service', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.scan')),
            ],
        ),
    ]
