# Generated by Django 6.0.4 on 2026-05-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scan_profile',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='discovered_service',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='port',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='raw_output',
        ),
        migrations.AlterField(
            model_name='scan',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.asset'),
        ),
    ]
