# Generated by Django 6.0.4 on 2026-05-20 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_vulnerability_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cve',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='raw_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='title',
            field=models.TextField(),
        ),
    ]
