apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rhinnant/test-repo-1.git
    targetRevision: ci-cd-setup
    path: k8s/apps/django

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
