apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "83.6.0"
    chart: kube-prometheus-stack
    helm:
      releaseName: monitoring
      values: |
        alertmanager:
          enabled: true
        grafana:
          enabled: true
          adminPassword: admin
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki.monitoring:3100
              isDefault: false
              editable: true
        prometheus:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
