name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r .

  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Safety
        run: pip install safety

      - name: Run Safety
        run: safety check
